services:
  app:
    image: ghcr.io/leodots/petshop-ponto:latest
    container_name: petshop-ponto
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_INITIAL_PASSWORD: ${ADMIN_INITIAL_PASSWORD}
      STORE_NAME: ${STORE_NAME}
    networks:
      - infra

networks:
  infra:
    external: true
