name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: leodotsinc/.github/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      app_dir: petshop-ponto
      service_name: app
      container_name: petshop-ponto
      compose_file: docker-compose.prod.yml
